### ISSUE TITLE
Cluster support ?

### ISSUE THREAD

**Issue by pakokrew** [upringjs/upring#28]
Is it posible to use upring in a NodeJS Cluster ?

I have a basic example that runs in different process, but when I clusterise from one master process the connection seems to fail.

```
Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at Socket._healthCheck (dgram.js:637:11)
    at Socket.address (dgram.js:531:8)
    at Socket.obj.once (internal/cluster/child.js:83:25)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at startListening (dgram.js:156:10)
    at onHandle (dgram.js:251:9)
    at shared (internal/cluster/child.js:105:3)
    at Worker.send (internal/cluster/child.js:76:7)
dgram.js:637
    throw new errors.Error('ERR_SOCKET_DGRAM_NOT_RUNNING');
```

I'm simply using the exact same code for non-clusterised and clusterized, using throng to start the workers

**Comment by mcollina** [comment]
It is not possible to run it in cluster mode.
